#!/bin/sh
if [ -e .commit ]
    echo Running post-commit hook...
    then
    rm .commit
    echo Generating telereddit dependency graph
    mkdir -p docs
    pydeps --config setup.cfg telereddit -o docs/dependency-graph.svg
    git add docs/dependency-graph.svg
    git commit --amend -C HEAD --no-verify
fi
exit