#!/bin/sh
if [ -e .commit ]
    then
    rm .commit
    mkdir -p docs
    pydeps --config setup.cfg telereddit -o docs/dependency-graph.svg
    git add docs/dependency-graph.svg
    git commit --amend -C HEAD --no-verify
fi
exit