version: "2"
checks:
  argument-count:
    config:
      threshold: 7
  method-complexity:
    config:
      threshold: 15
plugins:
  duplication:
    enabled: true
  pep8:
    enabled: true
    max-line-length: 81
  apexmetrics:
    enabled: true
  bandit:
    enabled: true
  radon: 
    enabled: true
    config: 
      threshold: "C"
exclude_patterns:
  - "**/tests/"
  - "**/secret_*.py"
