name: docs

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        key: ${{ runner.os }}-pip-${{ hashFiles('./requirements/requirements.txt') }}-${{ hashFiles('**/docs.txt') }}-${{ hashFiles('**/test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r ./requirements/requirements.txt
        pip install -r ./requirements/docs.txt
        pip install -r ./requirements/test.txt

    - name: Unlock git-crypt files
      uses: zemuldo/git-crypt-unlock@v3.0-alpha-1
      env: 
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }} 

    - name: Generate documentation
      run: |
        rm -rf docs/telereddit
        pdoc --html --output-dir="docs/" --template-dir="docs/templates" --config show_source_code=False --force .
      env:
        TELEREDDIT_MACHINE: GITHUB

    - name: Deploy docs to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/telereddit
