name: Test

on:
  [push, pull_request]

# on:
#   push:
#     branches:
#     - master
#   pull_request:
#     types: [opened, synchronize, repoened, edited]
#     branches:
#     - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Unlock git-crypt files
      uses: zemuldo/git-crypt-unlock@master
      env: 
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and generate report
      run: | 
        pip install coverage
        coverage run -m unittest
      env:
        TELEREDDIT_MACHINE: 'GITHUB'

    - name: Upload reports to codecov.io
      uses: codecov/codecov-action@v1

    - name: Upload reports to Code Climate
      uses: paambaati/codeclimate-action@v2.6.0
      with:
        coverageCommand: coverage xml
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
