/** Generated by YAKINDU Statechart Tools code generator. */

#include "Telereddit.h"
#include "..\src\sc_types.h"

/*! \file Implementation of the state machine 'telereddit'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif
/* prototypes of all internal functions */
static sc_boolean check_r__choice_0_tr0_tr0(const Telereddit* handle);
static sc_boolean check_r__choice_1_tr0_tr0(const Telereddit* handle);
static sc_boolean check_r__choice_2_tr1_tr1(const Telereddit* handle);
static void effect_r__choice_0_tr0(Telereddit* handle);
static void effect_r__choice_0_tr1(Telereddit* handle);
static void effect_r__choice_1_tr0(Telereddit* handle);
static void effect_r__choice_1_tr1(Telereddit* handle);
static void effect_r__choice_2_tr1(Telereddit* handle);
static void effect_r__choice_2_tr0(Telereddit* handle);
static void enact_r_send_link(Telereddit* handle);
static void enact_r_send_subreddit(Telereddit* handle);
static void enact_r_delete_post(Telereddit* handle);
static void enact_r_edit_post(Telereddit* handle);
static void exact_r_send_subreddit_r_wait_for_api_response(Telereddit* handle);
static void exact_r_edit_post_r_wait_for_api_response(Telereddit* handle);
static void enseq_r_waiting_default(Telereddit* handle);
static void enseq_r_send_link_default(Telereddit* handle);
static void enseq_r_send_link_r_send_post_default(Telereddit* handle);
static void enseq_r_send_link_r_wait_for_api_response_default(Telereddit* handle);
static void enseq_r_send_subreddit_default(Telereddit* handle);
static void enseq_r_send_subreddit_r_send_post_default(Telereddit* handle);
static void enseq_r_send_subreddit_r_wait_for_api_response_default(Telereddit* handle);
static void enseq_r_delete_post_default(Telereddit* handle);
static void enseq_r_edit_post_default(Telereddit* handle);
static void enseq_r_edit_post_r_edit_post_default(Telereddit* handle);
static void enseq_r_edit_post_r_wait_for_api_response_default(Telereddit* handle);
static void enseq_r_default(Telereddit* handle);
static void enseq_r_send_link_r_default(Telereddit* handle);
static void enseq_r_send_subreddit_r_default(Telereddit* handle);
static void enseq_r_edit_post_r_default(Telereddit* handle);
static void exseq_r_waiting(Telereddit* handle);
static void exseq_r_send_link(Telereddit* handle);
static void exseq_r_send_link_r_send_post(Telereddit* handle);
static void exseq_r_send_link_r_wait_for_api_response(Telereddit* handle);
static void exseq_r_send_subreddit(Telereddit* handle);
static void exseq_r_send_subreddit_r_send_post(Telereddit* handle);
static void exseq_r_send_subreddit_r_wait_for_api_response(Telereddit* handle);
static void exseq_r_delete_post(Telereddit* handle);
static void exseq_r_edit_post(Telereddit* handle);
static void exseq_r_edit_post_r_edit_post(Telereddit* handle);
static void exseq_r_edit_post_r_wait_for_api_response(Telereddit* handle);
static void exseq_r(Telereddit* handle);
static void exseq_r_send_link_r(Telereddit* handle);
static void exseq_r_send_subreddit_r(Telereddit* handle);
static void exseq_r_edit_post_r(Telereddit* handle);
static void react_r__choice_0(Telereddit* handle);
static void react_r__choice_1(Telereddit* handle);
static void react_r__choice_2(Telereddit* handle);
static void react_r__entry_Default(Telereddit* handle);
static void react_r_send_link_r__entry_Default(Telereddit* handle);
static void react_r_send_subreddit_r__entry_Default(Telereddit* handle);
static void react_r_edit_post_r__entry_Default(Telereddit* handle);
static sc_boolean react(Telereddit* handle);
static sc_boolean r_waiting_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_send_link_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_send_link_r_send_post_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_send_link_r_wait_for_api_response_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_send_subreddit_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_send_subreddit_r_send_post_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_send_subreddit_r_wait_for_api_response_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_delete_post_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_edit_post_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_edit_post_r_edit_post_react(Telereddit* handle, const sc_boolean try_transition);
static sc_boolean r_edit_post_r_wait_for_api_response_react(Telereddit* handle, const sc_boolean try_transition);
static void clearInEvents(Telereddit* handle);
static void clearOutEvents(Telereddit* handle);

const sc_integer TELEREDDIT_TELEREDDITIFACEAPI_OK = 1;
const sc_integer TELEREDDIT_TELEREDDITIFACEAPI_ERROR = 0;
const sc_integer TELEREDDIT_TELEREDDITIFACEAPI_NONE = 2;
const sc_integer TELEREDDIT_TELEREDDITIFACEAPI_MAX_TRIES = 3;


void telereddit_init(Telereddit* handle)
{
	sc_integer i;
	
	for (i = 0; i < TELEREDDIT_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Telereddit_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart telereddit */
	handle->internal.message = (sc_string) "";
	handle->ifaceApi.status = 0;
	handle->ifaceApi.tries = 0;
}

void telereddit_enter(Telereddit* handle)
{
	/* Default enter sequence for statechart telereddit */
	enseq_r_default(handle);
}

void telereddit_runCycle(Telereddit* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < TELEREDDIT_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case Telereddit_r_waiting:
		{
			r_waiting_react(handle, bool_true);
			break;
		}
		case Telereddit_r_send_link_r_send_post:
		{
			r_send_link_r_send_post_react(handle, bool_true);
			break;
		}
		case Telereddit_r_send_link_r_wait_for_api_response:
		{
			r_send_link_r_wait_for_api_response_react(handle, bool_true);
			break;
		}
		case Telereddit_r_send_subreddit_r_send_post:
		{
			r_send_subreddit_r_send_post_react(handle, bool_true);
			break;
		}
		case Telereddit_r_send_subreddit_r_wait_for_api_response:
		{
			r_send_subreddit_r_wait_for_api_response_react(handle, bool_true);
			break;
		}
		case Telereddit_r_delete_post:
		{
			r_delete_post_react(handle, bool_true);
			break;
		}
		case Telereddit_r_edit_post_r_edit_post:
		{
			r_edit_post_r_edit_post_react(handle, bool_true);
			break;
		}
		case Telereddit_r_edit_post_r_wait_for_api_response:
		{
			r_edit_post_r_wait_for_api_response_react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void telereddit_exit(Telereddit* handle)
{
	/* Default exit sequence for statechart telereddit */
	exseq_r(handle);
}

sc_boolean telereddit_isActive(const Telereddit* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < TELEREDDIT_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Telereddit_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean telereddit_isFinal(const Telereddit* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean telereddit_isStateActive(const Telereddit* handle, TeleredditStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Telereddit_r_waiting :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_WAITING] == Telereddit_r_waiting
			);
			break;
		case Telereddit_r_send_link :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_LINK] >= Telereddit_r_send_link
				&& handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_LINK] <= Telereddit_r_send_link_r_wait_for_api_response);
			break;
		case Telereddit_r_send_link_r_send_post :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_LINK_R_SEND_POST] == Telereddit_r_send_link_r_send_post
			);
			break;
		case Telereddit_r_send_link_r_wait_for_api_response :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_LINK_R_WAIT_FOR_API_RESPONSE] == Telereddit_r_send_link_r_wait_for_api_response
			);
			break;
		case Telereddit_r_send_subreddit :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_SUBREDDIT] >= Telereddit_r_send_subreddit
				&& handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_SUBREDDIT] <= Telereddit_r_send_subreddit_r_wait_for_api_response);
			break;
		case Telereddit_r_send_subreddit_r_send_post :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_SUBREDDIT_R_SEND_POST] == Telereddit_r_send_subreddit_r_send_post
			);
			break;
		case Telereddit_r_send_subreddit_r_wait_for_api_response :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_SEND_SUBREDDIT_R_WAIT_FOR_API_RESPONSE] == Telereddit_r_send_subreddit_r_wait_for_api_response
			);
			break;
		case Telereddit_r_delete_post :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_DELETE_POST] == Telereddit_r_delete_post
			);
			break;
		case Telereddit_r_edit_post :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_EDIT_POST] >= Telereddit_r_edit_post
				&& handle->stateConfVector[SCVI_TELEREDDIT_R_EDIT_POST] <= Telereddit_r_edit_post_r_wait_for_api_response);
			break;
		case Telereddit_r_edit_post_r_edit_post :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_EDIT_POST_R_EDIT_POST] == Telereddit_r_edit_post_r_edit_post
			);
			break;
		case Telereddit_r_edit_post_r_wait_for_api_response :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TELEREDDIT_R_EDIT_POST_R_WAIT_FOR_API_RESPONSE] == Telereddit_r_edit_post_r_wait_for_api_response
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Telereddit* handle)
{
	handle->ifaceUser.choose_send_link_raised = bool_false;
	handle->ifaceUser.choose_send_subreddit_raised = bool_false;
	handle->ifaceUser.choose_more_posts_raised = bool_false;
	handle->ifaceUser.choose_delete_post_raised = bool_false;
	handle->ifaceUser.choose_edit_post_raised = bool_false;
	handle->ifaceApi.response_raised = bool_false;
}

static void clearOutEvents(Telereddit* handle)
{
	SC_UNUSED(handle);
}

void teleredditIfaceUser_raise_choose_send_link(Telereddit* handle)
{
	handle->ifaceUser.choose_send_link_raised = bool_true;
	
	telereddit_runCycle(handle);
}
void teleredditIfaceUser_raise_choose_send_subreddit(Telereddit* handle)
{
	handle->ifaceUser.choose_send_subreddit_raised = bool_true;
	
	telereddit_runCycle(handle);
}
void teleredditIfaceUser_raise_choose_more_posts(Telereddit* handle)
{
	handle->ifaceUser.choose_more_posts_raised = bool_true;
	
	telereddit_runCycle(handle);
}
void teleredditIfaceUser_raise_choose_delete_post(Telereddit* handle)
{
	handle->ifaceUser.choose_delete_post_raised = bool_true;
	
	telereddit_runCycle(handle);
}
void teleredditIfaceUser_raise_choose_edit_post(Telereddit* handle)
{
	handle->ifaceUser.choose_edit_post_raised = bool_true;
	
	telereddit_runCycle(handle);
}


void teleredditIfaceApi_raise_response(Telereddit* handle)
{
	handle->ifaceApi.response_raised = bool_true;
	
	telereddit_runCycle(handle);
}


sc_integer teleredditIfaceApi_get_oK(const Telereddit* handle)
{
	SC_UNUSED(handle);
	return TELEREDDIT_TELEREDDITIFACEAPI_OK;
}
sc_integer teleredditIfaceApi_get_eRROR(const Telereddit* handle)
{
	SC_UNUSED(handle);
	return TELEREDDIT_TELEREDDITIFACEAPI_ERROR;
}
sc_integer teleredditIfaceApi_get_nONE(const Telereddit* handle)
{
	SC_UNUSED(handle);
	return TELEREDDIT_TELEREDDITIFACEAPI_NONE;
}
sc_integer teleredditIfaceApi_get_mAX_TRIES(const Telereddit* handle)
{
	SC_UNUSED(handle);
	return TELEREDDIT_TELEREDDITIFACEAPI_MAX_TRIES;
}
sc_integer teleredditIfaceApi_get_status(const Telereddit* handle)
{
	return handle->ifaceApi.status;
}
void teleredditIfaceApi_set_status(Telereddit* handle, sc_integer value)
{
	handle->ifaceApi.status = value;
}
sc_integer teleredditIfaceApi_get_tries(const Telereddit* handle)
{
	return handle->ifaceApi.tries;
}
void teleredditIfaceApi_set_tries(Telereddit* handle, sc_integer value)
{
	handle->ifaceApi.tries = value;
}

/* implementations of all internal functions */

static sc_boolean check_r__choice_0_tr0_tr0(const Telereddit* handle)
{
	return (handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_OK);
}

static sc_boolean check_r__choice_1_tr0_tr0(const Telereddit* handle)
{
	return (handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_OK);
}

static sc_boolean check_r__choice_2_tr1_tr1(const Telereddit* handle)
{
	return (handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_OK);
}

static void effect_r__choice_0_tr0(Telereddit* handle)
{
	handle->internal.message = (sc_string) "Post sent";
	enseq_r_waiting_default(handle);
}

static void effect_r__choice_0_tr1(Telereddit* handle)
{
	handle->internal.message = (sc_string) "Post not sent due to an api error";
	enseq_r_waiting_default(handle);
}

static void effect_r__choice_1_tr0(Telereddit* handle)
{
	handle->internal.message = (sc_string) "Post sent";
	enseq_r_waiting_default(handle);
}

static void effect_r__choice_1_tr1(Telereddit* handle)
{
	handle->internal.message = (sc_string) "Post not sent due to an api error";
	enseq_r_waiting_default(handle);
}

static void effect_r__choice_2_tr1(Telereddit* handle)
{
	handle->internal.message = (sc_string) "Post edited";
	enseq_r_waiting_default(handle);
}

static void effect_r__choice_2_tr0(Telereddit* handle)
{
	handle->internal.message = (sc_string) "Post not edited due to an api error";
	enseq_r_waiting_default(handle);
}

/* Entry action for state 'send_link'. */
static void enact_r_send_link(Telereddit* handle)
{
	/* Entry action for state 'send_link'. */
	handle->ifaceApi.status = TELEREDDIT_TELEREDDITIFACEAPI_NONE;
	handle->internal.message = (sc_string) "";
}

/* Entry action for state 'send_subreddit'. */
static void enact_r_send_subreddit(Telereddit* handle)
{
	/* Entry action for state 'send_subreddit'. */
	handle->ifaceApi.status = TELEREDDIT_TELEREDDITIFACEAPI_NONE;
	handle->ifaceApi.tries = 0;
	handle->internal.message = (sc_string) "";
	handle->ifaceApi.status = TELEREDDIT_TELEREDDITIFACEAPI_NONE;
	handle->ifaceApi.tries = 0;
	handle->internal.message = (sc_string) "";
}

/* Entry action for state 'delete_post'. */
static void enact_r_delete_post(Telereddit* handle)
{
	/* Entry action for state 'delete_post'. */
	handle->ifaceApi.status = TELEREDDIT_TELEREDDITIFACEAPI_OK;
}

/* Entry action for state 'edit_post'. */
static void enact_r_edit_post(Telereddit* handle)
{
	/* Entry action for state 'edit_post'. */
	handle->ifaceApi.status = TELEREDDIT_TELEREDDITIFACEAPI_NONE;
	handle->ifaceApi.tries = 0;
	handle->internal.message = (sc_string) "";
}

/* Exit action for state 'wait_for_api_response'. */
static void exact_r_send_subreddit_r_wait_for_api_response(Telereddit* handle)
{
	/* Exit action for state 'wait_for_api_response'. */
	if ((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_ERROR))
	{ 
		handle->ifaceApi.tries++;
	} 
}

/* Exit action for state 'wait_for_api_response'. */
static void exact_r_edit_post_r_wait_for_api_response(Telereddit* handle)
{
	/* Exit action for state 'wait_for_api_response'. */
	if ((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_ERROR))
	{ 
		handle->ifaceApi.tries++;
	} 
}

/* 'default' enter sequence for state waiting */
static void enseq_r_waiting_default(Telereddit* handle)
{
	/* 'default' enter sequence for state waiting */
	handle->stateConfVector[0] = Telereddit_r_waiting;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state send_link */
static void enseq_r_send_link_default(Telereddit* handle)
{
	/* 'default' enter sequence for state send_link */
	enact_r_send_link(handle);
	enseq_r_send_link_r_default(handle);
}

/* 'default' enter sequence for state send_post */
static void enseq_r_send_link_r_send_post_default(Telereddit* handle)
{
	/* 'default' enter sequence for state send_post */
	handle->stateConfVector[0] = Telereddit_r_send_link_r_send_post;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state wait_for_api_response */
static void enseq_r_send_link_r_wait_for_api_response_default(Telereddit* handle)
{
	/* 'default' enter sequence for state wait_for_api_response */
	handle->stateConfVector[0] = Telereddit_r_send_link_r_wait_for_api_response;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state send_subreddit */
static void enseq_r_send_subreddit_default(Telereddit* handle)
{
	/* 'default' enter sequence for state send_subreddit */
	enact_r_send_subreddit(handle);
	enseq_r_send_subreddit_r_default(handle);
}

/* 'default' enter sequence for state send_post */
static void enseq_r_send_subreddit_r_send_post_default(Telereddit* handle)
{
	/* 'default' enter sequence for state send_post */
	handle->stateConfVector[0] = Telereddit_r_send_subreddit_r_send_post;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state wait_for_api_response */
static void enseq_r_send_subreddit_r_wait_for_api_response_default(Telereddit* handle)
{
	/* 'default' enter sequence for state wait_for_api_response */
	handle->stateConfVector[0] = Telereddit_r_send_subreddit_r_wait_for_api_response;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state delete_post */
static void enseq_r_delete_post_default(Telereddit* handle)
{
	/* 'default' enter sequence for state delete_post */
	enact_r_delete_post(handle);
	handle->stateConfVector[0] = Telereddit_r_delete_post;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state edit_post */
static void enseq_r_edit_post_default(Telereddit* handle)
{
	/* 'default' enter sequence for state edit_post */
	enact_r_edit_post(handle);
	enseq_r_edit_post_r_default(handle);
}

/* 'default' enter sequence for state edit_post */
static void enseq_r_edit_post_r_edit_post_default(Telereddit* handle)
{
	/* 'default' enter sequence for state edit_post */
	handle->stateConfVector[0] = Telereddit_r_edit_post_r_edit_post;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state wait_for_api_response */
static void enseq_r_edit_post_r_wait_for_api_response_default(Telereddit* handle)
{
	/* 'default' enter sequence for state wait_for_api_response */
	handle->stateConfVector[0] = Telereddit_r_edit_post_r_wait_for_api_response;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for region r */
static void enseq_r_default(Telereddit* handle)
{
	/* 'default' enter sequence for region r */
	react_r__entry_Default(handle);
}

/* 'default' enter sequence for region r */
static void enseq_r_send_link_r_default(Telereddit* handle)
{
	/* 'default' enter sequence for region r */
	react_r_send_link_r__entry_Default(handle);
}

/* 'default' enter sequence for region r */
static void enseq_r_send_subreddit_r_default(Telereddit* handle)
{
	/* 'default' enter sequence for region r */
	react_r_send_subreddit_r__entry_Default(handle);
}

/* 'default' enter sequence for region r */
static void enseq_r_edit_post_r_default(Telereddit* handle)
{
	/* 'default' enter sequence for region r */
	react_r_edit_post_r__entry_Default(handle);
}

/* Default exit sequence for state waiting */
static void exseq_r_waiting(Telereddit* handle)
{
	/* Default exit sequence for state waiting */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state send_link */
static void exseq_r_send_link(Telereddit* handle)
{
	/* Default exit sequence for state send_link */
	exseq_r_send_link_r(handle);
}

/* Default exit sequence for state send_post */
static void exseq_r_send_link_r_send_post(Telereddit* handle)
{
	/* Default exit sequence for state send_post */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state wait_for_api_response */
static void exseq_r_send_link_r_wait_for_api_response(Telereddit* handle)
{
	/* Default exit sequence for state wait_for_api_response */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state send_subreddit */
static void exseq_r_send_subreddit(Telereddit* handle)
{
	/* Default exit sequence for state send_subreddit */
	exseq_r_send_subreddit_r(handle);
}

/* Default exit sequence for state send_post */
static void exseq_r_send_subreddit_r_send_post(Telereddit* handle)
{
	/* Default exit sequence for state send_post */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state wait_for_api_response */
static void exseq_r_send_subreddit_r_wait_for_api_response(Telereddit* handle)
{
	/* Default exit sequence for state wait_for_api_response */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	exact_r_send_subreddit_r_wait_for_api_response(handle);
}

/* Default exit sequence for state delete_post */
static void exseq_r_delete_post(Telereddit* handle)
{
	/* Default exit sequence for state delete_post */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state edit_post */
static void exseq_r_edit_post(Telereddit* handle)
{
	/* Default exit sequence for state edit_post */
	exseq_r_edit_post_r(handle);
}

/* Default exit sequence for state edit_post */
static void exseq_r_edit_post_r_edit_post(Telereddit* handle)
{
	/* Default exit sequence for state edit_post */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state wait_for_api_response */
static void exseq_r_edit_post_r_wait_for_api_response(Telereddit* handle)
{
	/* Default exit sequence for state wait_for_api_response */
	handle->stateConfVector[0] = Telereddit_last_state;
	handle->stateConfVectorPosition = 0;
	exact_r_edit_post_r_wait_for_api_response(handle);
}

/* Default exit sequence for region r */
static void exseq_r(Telereddit* handle)
{
	/* Default exit sequence for region r */
	/* Handle exit of all possible states (of telereddit.r) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Telereddit_r_waiting :
		{
			exseq_r_waiting(handle);
			break;
		}
		case Telereddit_r_send_link_r_send_post :
		{
			exseq_r_send_link_r_send_post(handle);
			break;
		}
		case Telereddit_r_send_link_r_wait_for_api_response :
		{
			exseq_r_send_link_r_wait_for_api_response(handle);
			break;
		}
		case Telereddit_r_send_subreddit_r_send_post :
		{
			exseq_r_send_subreddit_r_send_post(handle);
			break;
		}
		case Telereddit_r_send_subreddit_r_wait_for_api_response :
		{
			exseq_r_send_subreddit_r_wait_for_api_response(handle);
			break;
		}
		case Telereddit_r_delete_post :
		{
			exseq_r_delete_post(handle);
			break;
		}
		case Telereddit_r_edit_post_r_edit_post :
		{
			exseq_r_edit_post_r_edit_post(handle);
			break;
		}
		case Telereddit_r_edit_post_r_wait_for_api_response :
		{
			exseq_r_edit_post_r_wait_for_api_response(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r */
static void exseq_r_send_link_r(Telereddit* handle)
{
	/* Default exit sequence for region r */
	/* Handle exit of all possible states (of telereddit.r.send_link.r) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Telereddit_r_send_link_r_send_post :
		{
			exseq_r_send_link_r_send_post(handle);
			break;
		}
		case Telereddit_r_send_link_r_wait_for_api_response :
		{
			exseq_r_send_link_r_wait_for_api_response(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r */
static void exseq_r_send_subreddit_r(Telereddit* handle)
{
	/* Default exit sequence for region r */
	/* Handle exit of all possible states (of telereddit.r.send_subreddit.r) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Telereddit_r_send_subreddit_r_send_post :
		{
			exseq_r_send_subreddit_r_send_post(handle);
			break;
		}
		case Telereddit_r_send_subreddit_r_wait_for_api_response :
		{
			exseq_r_send_subreddit_r_wait_for_api_response(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r */
static void exseq_r_edit_post_r(Telereddit* handle)
{
	/* Default exit sequence for region r */
	/* Handle exit of all possible states (of telereddit.r.edit_post.r) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Telereddit_r_edit_post_r_edit_post :
		{
			exseq_r_edit_post_r_edit_post(handle);
			break;
		}
		case Telereddit_r_edit_post_r_wait_for_api_response :
		{
			exseq_r_edit_post_r_wait_for_api_response(handle);
			break;
		}
		default: break;
	}
}

/* The reactions of state null. */
static void react_r__choice_0(Telereddit* handle)
{
	/* The reactions of state null. */
	if (check_r__choice_0_tr0_tr0(handle) == bool_true)
	{ 
		effect_r__choice_0_tr0(handle);
	}  else
	{
		effect_r__choice_0_tr1(handle);
	}
}

/* The reactions of state null. */
static void react_r__choice_1(Telereddit* handle)
{
	/* The reactions of state null. */
	if (check_r__choice_1_tr0_tr0(handle) == bool_true)
	{ 
		effect_r__choice_1_tr0(handle);
	}  else
	{
		effect_r__choice_1_tr1(handle);
	}
}

/* The reactions of state null. */
static void react_r__choice_2(Telereddit* handle)
{
	/* The reactions of state null. */
	if (check_r__choice_2_tr1_tr1(handle) == bool_true)
	{ 
		effect_r__choice_2_tr1(handle);
	}  else
	{
		effect_r__choice_2_tr0(handle);
	}
}

/* Default react sequence for initial entry  */
static void react_r__entry_Default(Telereddit* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r_waiting_default(handle);
}

/* Default react sequence for initial entry  */
static void react_r_send_link_r__entry_Default(Telereddit* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r_send_link_r_send_post_default(handle);
}

/* Default react sequence for initial entry  */
static void react_r_send_subreddit_r__entry_Default(Telereddit* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r_send_subreddit_r_send_post_default(handle);
}

/* Default react sequence for initial entry  */
static void react_r_edit_post_r__entry_Default(Telereddit* handle)
{
	/* Default react sequence for initial entry  */
	enseq_r_edit_post_r_edit_post_default(handle);
}

static sc_boolean react(Telereddit* handle) {
	/* State machine reactions. */
	return bool_false;
	SC_UNUSED(handle);
}

static sc_boolean r_waiting_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state waiting. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceUser.choose_send_link_raised == bool_true)
		{ 
			exseq_r_waiting(handle);
			enseq_r_send_link_default(handle);
			react(handle);
		}  else
		{
			if (handle->ifaceUser.choose_send_subreddit_raised == bool_true)
			{ 
				exseq_r_waiting(handle);
				enseq_r_send_subreddit_default(handle);
				react(handle);
			}  else
			{
				if (handle->ifaceUser.choose_more_posts_raised == bool_true)
				{ 
					exseq_r_waiting(handle);
					enseq_r_send_subreddit_default(handle);
					react(handle);
				}  else
				{
					if (handle->ifaceUser.choose_delete_post_raised == bool_true)
					{ 
						exseq_r_waiting(handle);
						enseq_r_delete_post_default(handle);
						react(handle);
					}  else
					{
						if (handle->ifaceUser.choose_edit_post_raised == bool_true)
						{ 
							exseq_r_waiting(handle);
							enseq_r_edit_post_default(handle);
							react(handle);
						}  else
						{
							did_transition = bool_false;
						}
					}
				}
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean r_send_link_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state send_link. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		did_transition = bool_false;
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
	SC_UNUSED(handle);
}

static sc_boolean r_send_link_r_send_post_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state send_post. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_NONE))
		{ 
			exseq_r_send_link_r_send_post(handle);
			enseq_r_send_link_r_wait_for_api_response_default(handle);
			r_send_link_react(handle, bool_false);
		}  else
		{
			if ((handle->ifaceApi.status) != (TELEREDDIT_TELEREDDITIFACEAPI_NONE))
			{ 
				exseq_r_send_link(handle);
				react_r__choice_0(handle);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = r_send_link_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean r_send_link_r_wait_for_api_response_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state wait_for_api_response. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->ifaceApi.response_raised) == bool_true) && (((handle->ifaceApi.status) != (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) == bool_true))
		{ 
			exseq_r_send_link_r_wait_for_api_response(handle);
			enseq_r_send_link_r_send_post_default(handle);
			r_send_link_react(handle, bool_false);
		}  else
		{
			if (((handle->ifaceApi.response_raised) == bool_true) && (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) == bool_true))
			{ 
				exseq_r_send_link_r_wait_for_api_response(handle);
				enseq_r_send_link_r_wait_for_api_response_default(handle);
				r_send_link_react(handle, bool_false);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = r_send_link_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean r_send_subreddit_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state send_subreddit. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		did_transition = bool_false;
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
	SC_UNUSED(handle);
}

static sc_boolean r_send_subreddit_r_send_post_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state send_post. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) || ((((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_ERROR)) && ((handle->ifaceApi.tries) < (TELEREDDIT_TELEREDDITIFACEAPI_MAX_TRIES))) == bool_true))
		{ 
			exseq_r_send_subreddit_r_send_post(handle);
			enseq_r_send_subreddit_r_wait_for_api_response_default(handle);
			r_send_subreddit_react(handle, bool_false);
		}  else
		{
			if (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_OK)) || (((handle->ifaceApi.tries) >= (TELEREDDIT_TELEREDDITIFACEAPI_MAX_TRIES)) && ((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_ERROR))))
			{ 
				exseq_r_send_subreddit(handle);
				react_r__choice_1(handle);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = r_send_subreddit_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean r_send_subreddit_r_wait_for_api_response_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state wait_for_api_response. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->ifaceApi.response_raised) == bool_true) && (((handle->ifaceApi.status) != (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) == bool_true))
		{ 
			exseq_r_send_subreddit_r_wait_for_api_response(handle);
			enseq_r_send_subreddit_r_send_post_default(handle);
			r_send_subreddit_react(handle, bool_false);
		}  else
		{
			if (((handle->ifaceApi.response_raised) == bool_true) && (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) == bool_true))
			{ 
				exseq_r_send_subreddit_r_wait_for_api_response(handle);
				enseq_r_send_subreddit_r_wait_for_api_response_default(handle);
				r_send_subreddit_react(handle, bool_false);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = r_send_subreddit_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean r_delete_post_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state delete_post. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		exseq_r_delete_post(handle);
		handle->internal.message = (sc_string) "Post deleted";
		enseq_r_waiting_default(handle);
		react(handle);
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean r_edit_post_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state edit_post. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_OK)) || (((handle->ifaceApi.tries) >= (TELEREDDIT_TELEREDDITIFACEAPI_MAX_TRIES)) && ((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_ERROR))))
		{ 
			exseq_r_edit_post(handle);
			react_r__choice_2(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean r_edit_post_r_edit_post_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state edit_post. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) || ((((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_ERROR)) && ((handle->ifaceApi.tries) < (TELEREDDIT_TELEREDDITIFACEAPI_MAX_TRIES))) == bool_true))
		{ 
			exseq_r_edit_post_r_edit_post(handle);
			enseq_r_edit_post_r_wait_for_api_response_default(handle);
			r_edit_post_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = r_edit_post_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean r_edit_post_r_wait_for_api_response_react(Telereddit* handle, const sc_boolean try_transition) {
	/* The reactions of state wait_for_api_response. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->ifaceApi.response_raised) == bool_true) && (((handle->ifaceApi.status) != (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) == bool_true))
		{ 
			exseq_r_edit_post_r_wait_for_api_response(handle);
			enseq_r_edit_post_r_edit_post_default(handle);
			r_edit_post_react(handle, bool_false);
		}  else
		{
			if (((handle->ifaceApi.response_raised) == bool_true) && (((handle->ifaceApi.status) == (TELEREDDIT_TELEREDDITIFACEAPI_NONE)) == bool_true))
			{ 
				exseq_r_edit_post_r_wait_for_api_response(handle);
				enseq_r_edit_post_r_wait_for_api_response_default(handle);
				r_edit_post_react(handle, bool_false);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = r_edit_post_react(handle, try_transition);
	} 
	return did_transition;
}


